name: Publish Package to AWS CodeArtifact

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRet_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          
      - name: Get CodeArtifact Token
        run: |
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain ${{ vars.CODEARTIFACT_DOMAIN }} \
            --domain-owner ${{ vars.CODEARTIFACT_OWNER }} \
            --query authorizationToken \
            --output text)
          echo "//${{ vars.CODEARTIFACT_DOMAIN }}-${{ vars.CODEARTIFACT_OWNER }}.d.codeartifact.${{ vars.AWS_REGION }}.amazonaws.com/npm/${{ vars.CODEARTIFACT_REPOSITORY }}/:always-auth=true" >> .npmrc
          echo "//${{ vars.CODEARTIFACT_DOMAIN }}-${{ vars.CODEARTIFACT_OWNER }}.d.codeartifact.${{ vars.AWS_REGION }}.amazonaws.com/npm/${{ vars.CODEARTIFACT_REPOSITORY }}/:_authToken=${TOKEN}" >> .npmrc
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build package
        run: npm run build
        
      - name: Publish package
        run: npm publish